version: "3"
services:
  postgres:
    container_name: financial
    image: postgres:13
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=root
    ports:
      - "5435:5432"
    volumes:
      - ./.docker/postgres:/var/lib/postgresql/data